name: Deploy Lambda Function

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create ZIP
        run: zip -r function.zip .

      - name: Configure AWS Credentials
        uses: actions/setup-aws@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your region

      - name: Deploy to Lambda
        run: aws lambda update-function-code --function-name my-lambda-function --zip-file fileb://function.zip
