name: Deploy Lambda Function
on:
  push:
    branches: [main]
    
env:
  AWS_REGION : "us-east-2"

  # Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Replace with your desired Python version

      - name: Create ZIP
        run: zip -r jumble_src.zip src

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::381491860641:role/git-lambda-deployer
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Deploy to Lambda
        run: aws lambda publish-layer-version --layer-name jumble_game_layer --zip-file fileb://jumble_src.zip --compatible-runtiems python3.9

